import { Task, Note } from '../types';

export const initialTasks: Task[] = [
  { id: 1, title: 'Complete project proposal', description: 'Finalize Q4 project proposal with budget estimates', priority: 'high', dueDate: '2025-10-20', completed: false, category: 'Work', tags: ['urgent', 'project'], createdAt: '2025-10-10' },
  { id: 2, title: 'Review code pull requests', description: 'Review and merge pending PRs from team members', priority: 'medium', dueDate: '2025-10-16', completed: false, category: 'Work', tags: ['code', 'review'], createdAt: '2025-10-12' },
  { id: 3, title: 'Grocery shopping', description: 'Buy vegetables, fruits, and pantry essentials', priority: 'low', dueDate: '2025-10-15', completed: true, category: 'Personal', tags: ['shopping', 'home'], createdAt: '2025-10-13' },
  { id: 4, title: 'Update documentation', description: 'Update API documentation for new endpoints', priority: 'medium', dueDate: '2025-10-18', completed: false, category: 'Work', tags: ['docs', 'api'], createdAt: '2025-10-11' },
  { id: 5, title: 'Team meeting prep', description: 'Prepare slides for quarterly review meeting', priority: 'high', dueDate: '2025-10-17', completed: false, category: 'Work', tags: ['meeting', 'presentation'], createdAt: '2025-10-14' },
  { id: 6, title: 'Gym workout', description: 'Cardio and strength training session', priority: 'low', dueDate: '2025-10-15', completed: false, category: 'Health', tags: ['fitness', 'exercise'], createdAt: '2025-10-13' },
  { id: 7, title: 'Pay utility bills', description: 'Electricity, water, and internet bills due', priority: 'high', dueDate: '2025-10-16', completed: false, category: 'Finance', tags: ['bills', 'payment'], createdAt: '2025-10-12' },
  { id: 8, title: 'Book dentist appointment', description: 'Schedule routine dental checkup', priority: 'medium', dueDate: '2025-10-22', completed: false, category: 'Health', tags: ['appointment', 'medical'], createdAt: '2025-10-14' },
  { id: 9, title: 'Fix bug in login module', description: 'Resolve authentication timeout issue', priority: 'high', dueDate: '2025-10-16', completed: true, category: 'Work', tags: ['bug', 'urgent'], createdAt: '2025-10-10' },
  { id: 10, title: 'Plan weekend trip', description: 'Research destinations and book accommodation', priority: 'low', dueDate: '2025-10-19', completed: false, category: 'Personal', tags: ['travel', 'planning'], createdAt: '2025-10-13' },
  { id: 11, title: 'Call mom', description: 'Weekly check-in call with family', priority: 'medium', dueDate: '2025-10-15', completed: false, category: 'Personal', tags: ['family', 'call'], createdAt: '2025-10-14' },
  { id: 12, title: 'Database backup', description: 'Perform weekly database backup and verification', priority: 'high', dueDate: '2025-10-17', completed: false, category: 'Work', tags: ['maintenance', 'backup'], createdAt: '2025-10-11' },
  { id: 13, title: 'Read book chapter', description: 'Finish chapter 5 of productivity book', priority: 'low', dueDate: '2025-10-20', completed: false, category: 'Personal', tags: ['reading', 'learning'], createdAt: '2025-10-12' },
  { id: 14, title: 'Client presentation', description: 'Present new feature demo to client stakeholders', priority: 'high', dueDate: '2025-10-18', completed: false, category: 'Work', tags: ['client', 'demo'], createdAt: '2025-10-13' },
  { id: 15, title: 'Car maintenance', description: 'Oil change and tire rotation service', priority: 'medium', dueDate: '2025-10-21', completed: false, category: 'Personal', tags: ['car', 'maintenance'], createdAt: '2025-10-14' },
  { id: 16, title: 'Write blog post', description: 'Draft article on React best practices', priority: 'low', dueDate: '2025-10-23', completed: false, category: 'Personal', tags: ['writing', 'blog'], createdAt: '2025-10-13' },
  { id: 17, title: 'Security audit', description: 'Review application security vulnerabilities', priority: 'high', dueDate: '2025-10-19', completed: false, category: 'Work', tags: ['security', 'audit'], createdAt: '2025-10-12' },
  { id: 18, title: 'Organize closet', description: 'Sort and donate unused clothes', priority: 'low', dueDate: '2025-10-24', completed: false, category: 'Personal', tags: ['home', 'organizing'], createdAt: '2025-10-14' },
  { id: 19, title: 'Submit expense report', description: 'File monthly expense reimbursement', priority: 'medium', dueDate: '2025-10-17', completed: false, category: 'Work', tags: ['finance', 'admin'], createdAt: '2025-10-11' },
  { id: 20, title: 'Learn TypeScript', description: 'Complete online TypeScript course module 3', priority: 'medium', dueDate: '2025-10-22', completed: false, category: 'Personal', tags: ['learning', 'coding'], createdAt: '2025-10-13' }
];

export const initialNotes: Note[] = [
  { id: 1, title: 'Meeting Notes - Q4 Planning', content: 'Discussed quarterly goals, budget allocation, and team expansion plans. Action items: finalize hiring timeline, review budget with finance.', category: 'Work', tags: ['meeting', 'planning'], createdAt: '2025-10-12', updatedAt: '2025-10-12' },
  { id: 2, title: 'Recipe: Pasta Carbonara', content: 'Ingredients: pasta, eggs, parmesan, pancetta. Cook pasta, mix eggs with cheese, combine with hot pasta and pancetta.', category: 'Personal', tags: ['recipe', 'cooking'], createdAt: '2025-10-10', updatedAt: '2025-10-11' },
  { id: 3, title: 'Project Ideas', content: 'Mobile task manager with offline support, Real-time collaboration tool, AI-powered note organizer, Habit tracking app with analytics', category: 'Work', tags: ['ideas', 'projects'], createdAt: '2025-10-09', updatedAt: '2025-10-13' },
  { id: 4, title: 'Book Summary: Atomic Habits', content: 'Key takeaways: Small changes compound over time, Focus on systems not goals, Make habits obvious and attractive, Track progress consistently', category: 'Personal', tags: ['books', 'learning'], createdAt: '2025-10-08', updatedAt: '2025-10-08' },
  { id: 5, title: 'API Design Notes', content: 'RESTful principles: Use proper HTTP methods, Consistent naming conventions, Version your API, Implement proper error handling, Add rate limiting', category: 'Work', tags: ['api', 'development'], createdAt: '2025-10-11', updatedAt: '2025-10-11' },
  { id: 6, title: 'Travel Checklist', content: 'Passport, tickets, hotel confirmation, travel insurance, medications, chargers, camera, comfortable shoes, weather-appropriate clothing', category: 'Personal', tags: ['travel', 'checklist'], createdAt: '2025-10-13', updatedAt: '2025-10-14' },
  { id: 7, title: 'Client Feedback', content: 'Client requested: Faster load times, Dark mode option, Export to PDF feature, Mobile app version, Better search functionality', category: 'Work', tags: ['feedback', 'client'], createdAt: '2025-10-12', updatedAt: '2025-10-12' },
  { id: 8, title: 'Workout Routine', content: 'Monday: Chest & Triceps, Tuesday: Back & Biceps, Wednesday: Legs, Thursday: Shoulders, Friday: Full body, Weekend: Cardio & Rest', category: 'Health', tags: ['fitness', 'exercise'], createdAt: '2025-10-10', updatedAt: '2025-10-10' },
  { id: 9, title: 'Gift Ideas', content: 'Mom: Gardening tools, Dad: Book collection, Sister: Art supplies, Best friend: Concert tickets, Colleague: Coffee gift set', category: 'Personal', tags: ['shopping', 'gifts'], createdAt: '2025-10-09', updatedAt: '2025-10-13' },
  { id: 10, title: 'Database Schema', content: 'Users table: id, email, password_hash, created_at. Tasks table: id, user_id, title, description, due_date, priority. Notes table: id, user_id, title, content, tags', category: 'Work', tags: ['database', 'schema'], createdAt: '2025-10-11', updatedAt: '2025-10-11' },
  { id: 11, title: 'Learning Resources', content: 'React docs, TypeScript handbook, Node.js best practices, MySQL optimization guide, Tailwind CSS components, Design patterns book', category: 'Personal', tags: ['learning', 'resources'], createdAt: '2025-10-08', updatedAt: '2025-10-12' },
  { id: 12, title: 'Budget Planning', content: 'Monthly expenses: Rent $1200, Utilities $150, Groceries $400, Transportation $100, Entertainment $200, Savings goal $500', category: 'Finance', tags: ['budget', 'planning'], createdAt: '2025-10-13', updatedAt: '2025-10-13' }
];
